### ISSUE TITLE
API test fails sporadically in CI

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#11]
For example, it fails here on a PR that adds a license: https://github.com/web3-storage/web3.storage/runs/2954531337?check_suite_focus=true

```
Run npm test --workspace packages/api

> web3.storage-api@0.0.0 test
> playwright-test "test/**/*.spec.js" --sw src/index.js

- Setting up chromium
(node:2358) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/package.json imported from /home/runner/work/web3.storage/web3.storage/node_modules/playwright-test/src/utils/index.js.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

chromium v878941 downloaded to /home/runner/.cache/ms-playwright/chromium-878941
✔ chromium set up
- Bundling tests
✔ Bundling tests
Failed to load resource: the server responded with a status of 404 ()
http://localhost:3000/bundle-out.js
✖ Running tests failed.
page.addScriptTag: Evaluation failed: Error: Failed to load script at http://localhost:3000/bundle-out.js
    at HTMLScriptElement.script.onerror (eval at evaluate (:303:29), <anonymous>:8:82)
Error
    at Object.captureStackTrace (/home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/utils/stackTrace.js:50:19)
    at Connection.sendMessageToServer (/home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/client/connection.js:65:48)
    at Proxy.<anonymous> (/home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/client/channelOwner.js:64:61)
    at /home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/client/frame.js:269:70
    at Frame._wrapApiCall (/home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/client/channelOwner.js:77:34)
    at Frame.addScriptTag (/home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/client/frame.js:263:21)
    at /home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/client/page.js:269:60
    at Page._attributeToPage (/home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/client/page.js:238:20)
    at Page.addScriptTag (/home/runner/work/web3.storage/web3.storage/node_modules/playwright-core/lib/client/page.js:269:21)
    at MochaRunner.runTests (file:///home/runner/work/web3.storage/web3.storage/node_modules/playwright-test/src/runner.js:226:20)
    at async MochaRunner.runTests (file:///home/runner/work/web3.storage/web3.storage/node_modules/playwright-test/src/runner-mocha.js:52:5)
    at async MochaRunner.run (file:///home/runner/work/web3.storage/web3.storage/node_modules/playwright-test/src/runner.js:270:7)
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: web3.storage-api@0.0.0 
npm ERR!   at location: /home/runner/work/web3.storage/web3.storage/packages/api 
Error: Process completed with exit code 1.
```

**Comment by olizilla** [comment]
Is fixed in #40
