### ISSUE TITLE
Error at /user/account when user has no pinned storage

### ISSUE THREAD

**Issue by adamalton** [web3-storage/web3.storage#1347]
If you create a new account with no uploaded files, when you load the `/account/` page, the API call to `/user/account` returns a 500 status. I'm pretty sure (but not 100%) that this is caused by the user having no pinned files, and our code not handling that case.

The page correctly displays `0B of 1TiB used`, but I think that's because `0` is the fallback.

![Screenshot 2022-05-23 at 13 05 15](https://user-images.githubusercontent.com/270255/169816511-17e39e66-749f-4467-aeea-835462028e4c.png)

```shell
Error: Invalid number.
    at parseTextToNumber (web3.storage/packages/api/dist/worker.mjs:55534:11)
    at DBClient.getUsedStorage (web3.storage/packages/api/dist/worker.mjs:55684:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at userAccountGet (web3.storage/packages/api/dist/worker.mjs:65559:23)
    at web3.storage/packages/api/dist/worker.mjs:47566:22
    at Object.handle (web3.storage/packages/api/dist/worker.mjs:2046:22)
    at Object.fetch (web3.storage/packages/api/dist/worker.mjs:67855:18)
    at EventTarget.[kDispatchFetch] (web3.storage/node_modules/@miniflare/core/src/standards/event.ts:359:13)
    at Server.<anonymous> (web3.storage/node_modules/@miniflare/http-server/src/index.ts:168:20)
GET /user/account 500 Internal Server Error (1697.69ms, waitUntil: 1760.45ms)
```

The problem occurs in `packages/db/index.js` in `getUsedStorage` where the returned `psa_pinned` value from the `user_used_storage` SQL function is `undefined`. This is then passed to `parseTextToNumber`, which blows up.

**Comment by adamalton** [comment]
This isn't a bug, there was a migration that I hadn't applied 🤦
