### ISSUE TITLE
GET /car should fetch from cluster rather than gateway

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#138]
Fetching cars from the gateway was a quick fix while we didn't have a cluster, but I'm now getting sporadic failures on gets for CIDs that i know are pinned on cluster.

```
w3 get bafybeig2girrvm6wjis6xuqaqvoxhfejuk2bwv4bfzpjhlahsume26ufjy
file:///Users/oli/Code/web3-storage/web3.storage/packages/client/src/lib.js:181
        throw new Error(`${res.status} ${res.statusText}`)
              ^

Error: 522 
    at Function.get (file:///Users/oli/Code/web3-storage/web3.storage/packages/client/src/lib.js:181:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async get (file:///Users/oli/Code/web3-storage/web3.storage/packages/w3/index.js:86:15)
```

**Comment by alanshaw** [comment]
When we spoke about this we decided to fetch from our own gateway, so that our Cluster wasn't directly in the line of fire for reads. I'm going to update the title to reflect that.

**Comment by dchoi27** [comment]
Also explore Cloudflare caching
