### ISSUE TITLE
React serve -s build  Uncaught (in promise) TypeError: Invalid attempt to iterate non-iterable instance.

### ISSUE THREAD

**Issue by AlGokk** [web3-storage/web3.storage#1568]
If I run `serve -s build` I am getting some strange issues but it works with` npm run dev`. 

**Method**
```
async function retrieveFiles (cid) {
  const client = makeStorageClient()
  const res = await client.get(cid)
  console.log(`Got a response! [${res.status}] ${res.statusText}`)
  if (!res.ok) {
    throw new Error(`failed to get ${cid} - [${res.status}] ${res.statusText}`)
  }

  // unpack File objects from the response
  const files = await res.files()
  for (const file of files) {
    console.log(`${file.cid} -- ${file.path} -- ${file.size}`)
  }
}
```

**Error**
```
2.748bfab5.chunk.js:2 Uncaught (in promise) TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at i (2.748bfab5.chunk.js:2:32917)
    at 2.748bfab5.chunk.js:2:1739931
    at f (2.748bfab5.chunk.js:2:1396)
    at Generator._invoke (2.748bfab5.chunk.js:2:1149)
    at Generator.next (2.748bfab5.chunk.js:2:1759)
    at f (2.748bfab5.chunk.js:2:1396)
    at i (2.748bfab5.chunk.js:2:1820)
    at 2.748bfab5.chunk.js:2:2192
    at new Promise (<anonymous>)
    at n (2.748bfab5.chunk.js:2:2171)
```

**package.json**
```
{
  "name": "blueberrypay",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@apollo/client": "^3.6.2",
    "@craco/craco": "^6.4.3",
    "@headlessui/react": "^1.5.0",
    "@heroicons/react": "^1.0.6",
    "@tailwindcss/forms": "^0.5.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/crypto-js": "^4.1.1",
    "@types/jest": "^27.4.1",
    "@types/node": "^16.11.39",
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.2",
    "@walletconnect/web3-provider": "^1.7.8",
    "axios": "^0.26.1",
    "body-parser": "^1.20.0",
    "cors": "^2.8.5",
    "crypto-js": "^4.1.1",
    "eth-permit": "^0.2.1",
    "ethers": "^5.6.4",
    "express": "^4.17.3",
    "graphql": "^16.4.0",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.5.24",
    "moment": "^2.29.3",
    "mongoose": "^6.1.30",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.3.0",
    "react-scripts": "^4.0.3",
    "react-window": "^1.8.7",
    "styled-components": "^5.3.5",
    "typescript": "^4.6.3",
    "web-vitals": "^2.1.4",
    "web3.storage": "^4.2.0"
  },
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject",
    "server": "nodemon src/server/server.js",
    "dev": "concurrently --kill-others \"npm run start\" \"npm run server\""
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/react-window": "^1.8.5",
    "autoprefixer": "^9.8.8",
    "concurrently": "^7.1.0",
    "postcss": "^7.0.39",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.17"
  }
}
```

**Comment by vasco-santos** [comment]
Thanks for reporting this @AlGokk 

Did you have a chance to try to debug this and inspect what is the `files` const given it is not an iterable?

This looks like a bundle issue, did you try plain create react app with this?

**Comment by vasco-santos** [comment]
Closing for lack of activity. @AlGokk let us know if you are still blocked here so that we can try to help
