### ISSUE TITLE
`w3` explodes on first run.

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#167]
you can never test enough things.
```
 npm i -g @web3-storage/w3 --force                                                                                                                                   14:58:03
npm WARN using --force Recommended protections disabled.

added 272 packages, and audited 273 packages in 3s

52 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

~
❯ w3                                                                                                                                                                  14:58:13
/usr/local/lib/node_modules/@web3-storage/w3/node_modules/conf/dist/source/index.js:91
                throw new Error('Project name could not be inferred. Please specify the `projectName` option.');
                      ^

Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Conf (/usr/local/lib/node_modules/@web3-storage/w3/node_modules/conf/dist/source/index.js:91:23)
    at file:///usr/local/lib/node_modules/@web3-storage/w3/index.js:8:16
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
```

**Comment by olizilla** [comment]
https://github.com/sindresorhus/conf/issues/150
