### ISSUE TITLE
Sporadic pinning failure

### ISSUE THREAD

**Issue by olizilla** [web3-storage/web3.storage#2217]
Current hypothesis is that `147.75.84.119` is not having a good time.

```
    "code": "FETCH_GET_PIN",
    "cid": "bafkreihjc2vfq5wwicz4ayt37t3wlfmc54dtzdjc6kvazqwtx3zwusjqoy",
    "endpoint": "https://web3.storage.ipfscluster.io/api/",
    "err": "[ECONNREFUSED] request to https://web3.storage.ipfscluster.io/api//pins/bafkreihjc2vfq5wwicz4ayt37t3wlfmc54dtzdjc6kvazqwtx3zwusjqoy failed, reason: connect ECONNREFUSED 147.75.84.119:443\nFetchError: request to https://web3.storage.ipfscluster.io/api//pins/bafkreihjc2vfq5wwicz4ayt37t3wlfmc54dtzdjc6kvazqwtx3zwusjqoy failed, reason: connect ECONNREFUSED 147.75.84.119:443\n    at ClientRequest.<anonymous> (file:///var/task/api/basic/add-pin-router.js:39840:14)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
    "msg": "Fetch for get pin failed"
    ```

**Comment by olizilla** [comment]
```
    "code": "FETCH_GET_PIN",
    "cid": "bafkreiet674t4emhpq42tuggcbyw4snv2mpavnrtgh5fnuwcvzppmhnjfm",
    "endpoint": "https://web3.storage.ipfscluster.io/api/",
    "err": "[ECONNREFUSED] request to https://web3.storage.ipfscluster.io/api//pins/bafkreiet674t4emhpq42tuggcbyw4snv2mpavnrtgh5fnuwcvzppmhnjfm failed, reason: connect ECONNREFUSED 147.75.84.119:443\nFetchError: request to https://web3.storage.ipfscluster.io/api//pins/bafkreiet674t4emhpq42tuggcbyw4snv2mpavnrtgh5fnuwcvzppmhnjfm failed, reason: connect ECONNREFUSED 147.75.84.119:443\n    at ClientRequest.<anonymous> (file:///var/task/api/basic/add-pin-router.js:39840:14)\n    at ClientRequest.emit (node:events:527:28)\n  
```

**Comment by olizilla** [comment]
The node was bounced and pickup was rolled out with additional retrys.
