### ISSUE TITLE
Support for direct car file uploading through w3 cli

### ISSUE THREAD

**Issue by jonyg80** [web3-storage/web3.storage#357]
It would be good to have option to provide path of .car file to w3 cli for uploading to web3.storage

**Comment by jonyg80** [comment]
Sorry, I can't

**Comment by mehulagg** [comment]
I had tried to implement this but can't succeed. Link to code :- https://github.com/mehulagg/web3.storage/blob/feat/car_w3/packages/w3/index.js#L208
Getting below mentioned error on `CarIndexedReader.fromFile(path)` step
```
(node:3900) UnhandledPromiseRejectionWarning: ReferenceError: CarIndexedReader is not defined
    at putCar (file:///workspaces/web3.storage/packages/w3/index.js:235:21)
    at Sade.parse (/workspaces/web3.storage/packages/w3/node_modules/sade/lib/index.js:189:56)
    at file:///workspaces/web3.storage/packages/w3/bin.js:51:5
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:3900) ReferenceError: CarIndexedReader is not defined
    at putCar (file:///workspaces/web3.storage/packages/w3/index.js:235:21)
    at Sade.parse (/workspaces/web3.storage/packages/w3/node_modules/sade/lib/index.js:189:56)
    at file:///workspaces/web3.storage/packages/w3/bin.js:51:5
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(node:3900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

**Comment by mikeal** [comment]
@mehulagg probably due to using the indexed CAR reader on a CAR file without an index. I’d need to look at the data, but my best guess is that it’s expecting CARv2 and you’re passing CARv1. Try replacing `CarIndexedReader` with `CarReader`.

**Comment by mehulagg** [comment]
@mikeal Is there anyway to check whether the CAR file is CARv1 or CARv2 ?

**Comment by mehulagg** [comment]
I tried it with another CAR file and it worked .
