### ISSUE TITLE
Error uploading an html file

### ISSUE THREAD

**Issue by mh13test** [web3-storage/web3.storage#671]
Hello,

When uploading a .html file using the upload script, I get the following error. Any idea why?

Uploading 1 files
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///C:/Users/dan/Documents/quick/node_modules/@web-std/fetch/src/body.js:163:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async pRetry.retries (file:///C:/Users/dan/Documents/quick/node_modules/web3.storage/src/lib.js:172:23)
    at async RetryOperation._fn (C:\Users\dan\Documents\quick\node_modules\p-retry\index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
}

**Comment by atopal** [comment]
This is most likely a cloudflare issue. Could you please share the HTML file so we can repliacte and verify?

**Comment by dchoi27** [comment]
Hey there, just following up - if you're able to share the HTML file we can see what might be triggering the error.
